[project]
name = "filesystem-sim"
version = "0.1.0"
description = "Simulador de sistemas de archivos (contigua, enlazada, indexada) con CLI y UI opcional."
requires-python = ">=3.10"

[project.scripts]
fsim = "fsim.cli.main:main"
